development:
  adapter: postgresql
  encoding: unicode
  database: roomly_development
  pool: 5
  username: rtaff2012
  password: leonruss
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: roomly_test
  pool: 5
  username: rtaff2012
  password: leonruss
  host: localhost
