development:
  adapter: postgresql
  encoding: unicode
  database: roomly_development
  pool: 5
  username: jeff
  password:
  host: localhost 

test:
  adapter: postgresql
  encoding: unicode
  database: roomly_test
  pool: 5
  username: jeff
  password:
  host: localhost 
