development:
  adapter: postgresql
  encoding: unicode
  database: Ingredientio_development
  pool: 5
  username: mariamercedesmartinez
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Ingredientio_test
  pool: 5
  username: mariamercedesmartinez
  password:
