development:
  adapter: postgresql
  encoding: unicode
  database: ingredientio_development
  pool: 5
  username: T-Virus
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ingredientio_test
  pool: 5
  username: T-Virus
  password:
