development:
  adapter: postgresql
  encoding: unicode
  database: HG_development
  pool: 5
  username: wdi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: HG_test
  pool: 5
  username: wdi
  password:
